# upstream api {
#     server rest-with-spring-boot-erudio:8080; # Define o servidor backend da API
# }

server {
    listen 80; # Escuta na porta 80
    server_name localhost; # Define o nome do servidor

    location / {
        root   /usr/share/nginx/html; # Diretório raiz dos arquivos estáticos
        try_files $uri $uri/ /index.html; # Tenta servir arquivos ou redireciona para index.html
        index  index.html index.htm; # Arquivos de índice padrão
    }

    # location /api/ {
    #     # Configuração para requisições OPTIONS (preflight)
    #     if ($request_method = 'OPTIONS') {
    #         add_header 'Access-Control-Allow-Origin' 'http://localhost:3000';
    #         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
    #         add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range';
    #         add_header 'Access-Control-Max-Age' 1728000;
    #         add_header 'Content-Type' 'text/plain; charset=UTF-8';
    #         add_header 'Content-Length' 0;
    #         return 204; # Responde com status 204 (No Content)
    #     }

    #     # Configuração para as demais requisições
    #     add_header 'Access-Control-Allow-Origin' 'http://localhost:3000';
    #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
    #     add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range';
    #     add_header 'Access-Control-Allow-Credentials' 'true';

    #     proxy_pass http://api; # Redireciona as requisições para o backend da API
    #     proxy_http_version 1.1; # Usa HTTP 1.1 para conexões persistentes
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection 'upgrade';
    #     proxy_set_header Host $host;
    #     proxy_cache_bypass $http_upgrade; # Evita cache para conexões WebSocket
    # }

    error_page   500 502 503 504  /50x.html; # Página de erro para códigos 500, 502, 503, 504
    location = /50x.html {
        root   /usr/share/nginx/html; # Diretório raiz para páginas de erro
    }
}
